[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "neuronavigatar"
version = "0.1.0"
dependencies = [
    "numpy",
    "opencv-python", 
    "mediapipe",
    "PyQt5",
    "jdata",
    "importlib-resources; python_version < '3.9'",
]
[project.scripts]
neuronavigatar = "nnar:main"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools]
include-package-data = true

[tool.setuptools.package-data]
nnar = [
    'data/atlases/*.json',
    'data/models/*.json',
]